server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/dpsemu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false